version: 2
jobs:
  swc-config-update:
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout
      - run:
          name: Generate SWC definition
          shell: /bin/sh
          command: |
            git config --global user.email "$GIT_USER@users.noreply.github.com"
            git config --global user.name "$GIT_USER"
            echo "machine github.com login $GIT_USER password $GITHUB_TOKEN" > ~/.netrc
            cd scripts && npm install && npm run updateswc
            cd ../
            command=$(git status|grep -c 'export/swc-definition.json')
            if ((command > 0)); then
              git add export/
              git commit -m "Update SWC definition [ci skip]"
              git push -q https://${GITHUB_TOKEN}@github.com/${GIT_ORGANIZATION}/SWC-registry.git master
            fi

  swc-config-validate:
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout
      - run:
          name: Validate schema
          shell: /bin/sh
          command: |
            git config --global user.email "$GIT_USER@users.noreply.github.com"
            git config --global user.name "$GIT_USER"
            echo "machine github.com login $GIT_USER password $GITHUB_TOKEN" > ~/.netrc
            cd scripts/ && npm install jsonlint && npm run schema-validation && npm run updateswc

  deploy-gh-pages:
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout
      - run:
          name: Deploying website GitHub Pages
          command: |
            git config --global user.email "$GIT_USER@users.noreply.github.com"
            git config --global user.name "$GIT_USER"
            echo "machine github.com login $GIT_USER password $GITHUB_TOKEN" > ~/.netrc
            cd website && npm install && npm run generate-content && GIT_USER=$GIT_USER npm run publish-gh-pages

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy-gh-pages:
          filters:
            branches:
              only: website
              ignore: gh-pages
      - swc-config-update
          filters:
            branches:
              only: master
      - swc-config-validate
          filters:
            branches:
              ignore:
                - gh-pages
                - website